In [1]:
import numpy

In [2]:
import numpy as np

# 创建3x4的二维数组
arr = np.arange(1, 13).reshape(3, 4)
print("原始数组:\n", arr)

# 1. 打印数组属性
print("\n形状:", arr.shape)
print("维度:", arr.ndim)
print("数据类型:", arr.dtype)

# 2. 元素乘以2
arr_multiplied = arr * 2
print("\n乘以2后的数组:\n", arr_multiplied)

# 3. 重塑为4x3
arr_reshaped = arr.reshape(4, 3)
print("\n重塑为4x3的数组:\n", arr_reshaped)

原始数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

形状: (3, 4)
维度: 2
数据类型: int64

乘以2后的数组:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为4x3的数组:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第2行（索引为1）
row_2 = array[1, :]
print("第2行:", row_2)

# 2. 提取第3列（索引为2）
col_3 = array[:, 2]
print("第3列:", col_3)

# 3. 提取子数组（行1-2，列2-3）
sub_array = array[0:2, 1:3]
print("子数组:\n", sub_array)

# 4. 条件替换
array[array > 10] = 0
print("修改后的数组:\n", array)

第2行: [5 6 7 8]
第3列: [ 3  7 11 15]
子数组:
 [[2 3]
 [6 7]]
修改后的数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [4]:
import numpy as np

# 创建数组A和B
A = np.arange(1, 7).reshape(3, 2)
B = np.array([10, 20])

print("数组A:\n", A)
print("数组B:", B)

# 1. 逐元素相加
add_result = A + B
print("\nA + B:\n", add_result)

# 2. 逐元素相乘
mul_result = A * B
print("\nA * B:\n", mul_result)

# 3. 每行点积
dot_result = np.dot(A, B)
print("\nA每行与B的点积:", dot_result)

# 等价写法
dot_result_alt = A @ B
print("(验证)点积结果:", dot_result_alt)

数组A:
 [[1 2]
 [3 4]
 [5 6]]
数组B: [10 20]

A + B:
 [[11 22]
 [13 24]
 [15 26]]

A * B:
 [[ 10  40]
 [ 30  80]
 [ 50 120]]

A每行与B的点积: [ 50 110 170]
(验证)点积结果: [ 50 110 170]
